#!/bin/sh

GEOIPDIR="/usr/share/GeoIP"

cd $GEOIPDIR
wget https://github.com/thytetgc/GeoIP/raw/master/GeoLite2-Country.tar.gz


tar zxvf GeoLite2-Country.tar.gz --strip-components=1 --wildcards GeoLite2-Country*/GeoLite2-Country.mmdb
rm GeoLite2-Country.tar.gz
